### PR TITLE
Use more standard form of release flag in `MESON_ARGS`

### PR DESCRIPTION
**Pull request by h-vetinari**
There are two different ways to set up a release flag to meson, `--buildtype release`, and `-Dbuildtype=release`. Apparently the latter is more common; at least it's the recommended way in the [docs](https://mesonbuild.com/Builtin-options.html#details-for-buildtype).

Since meson-python will by default add `-Dbuildtype=release`, the fact that the compiler-activation does the other kind leads to a duplicate specification and forces us to strip it out again as follows (e.g. in [scipy](https://github.com/conda-forge/scipy-feedstock/blob/d5fd7f7982dc670786726344a98b57af35bc2b2c/recipe/build.sh#L15-L17), but affects all feedstocks using meson-python).
```
# meson-python already sets up a -Dbuildtype=release argument to meson, so
# we need to strip --buildtype out of MESON_ARGS or fail due to redundancy
MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"
```

To avoid this, use the more common form of the flag.

PS. Stumbled over this old [PR](https://github.com/conda-forge/scipy-feedstock/pull/232#discussion_r1176272687), where this was discussed with @rgommers
PPS. Sister PR of https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/98 (now https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/121)

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM. Thanks for working through the Meson build hiccups @h-vetinari!

**Comment by h-vetinari** [comment]
@isuruf, it seems meson 1.5.0 now deprecated the way we specify pkg-config here
```
DEPRECATION: "pkgconfig" entry is deprecated and should be replaced by "pkg-config"
```
so while we're fixing the meson setup in the compiler activation, I'd like to revive this PR.

**Comment by isuruf** [comment]
Let's do this only for new compiler versions and keep the older behaviour for clang 16 and gcc 12.

**Comment by h-vetinari** [comment]
> Let's do this only for new compiler versions and keep the older behaviour for clang 16 and gcc 12.

Good idea! IIUC, you only mean the release flag change here? The pkgconfig fix should be unconditional IMO (as feedstocks will keep pulling in newer meson even on old compilers).

**Comment by isuruf** [comment]
>  you only mean the release flag change here?

Yes

**Pull request merged**
