### PR TITLE
Remove std=c++14 from flags

### LINKED ISSUE #17: Using C++17
It looks like we are currently [requiring C++14 on macOS]( https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/de9142c89e4da28b4d5eabd2bd6c9f0d84e6fa64/recipe/build.sh#L7 ); whereas, we use [C++17 on Linux]( https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/eac83f495f22488f449ff6c564e000105f9c8346/recipe/conda_build_config.yaml#L30 ). Would it be possible to start using C++17 on macOS as well?

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #17

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
I would also

- Backport this to `11.x`
- Build `boost*=1.78` with this
- Build a new `abseil-cpp` with this
- Start the migration for both of them

**Comment by katietz** [comment]
Could you provide some details, why you consider to remove explicit std settings?  As so we will use default behavior of clang-driver, which might get different for different versions.  I agree that this way override of it via option gets more strict, but I might miss here something more interesting.

**Comment by xhochy** [comment]
This is based on @isuruf suggestion in https://github.com/conda-forge/clang-compiler-activation-feedstock/issues/17#issuecomment-831987409

**Comment by xhochy** [comment]
@isuruf Would you have time to look at this? I would be happy to bring this forward.

**Comment by isuruf** [comment]
@katietz, the issue with an explicit -std=c++14 is that it circumvents most build systems C++ setting. For some packages that need C++17, this forces them to use C++14. With clang 11, C++14 is the default, so this doesn't change anything for clang 11. However, it provides an easier way to use C++17 if a package needs it.

**Comment by isuruf** [comment]
@katietz, any thought on this?

**Comment by isuruf** [comment]
Ping @katietz

**Comment by jakirkham** [comment]
cc @anaconda-pkg-build

**Comment by isuruf** [comment]
Since I didn't hear from @katietz, going to assume this is okay.

**Comment by katietz** [comment]
thanks, got clear to me why. Sorry that I was a bit off, but had to do the 3.10 built out on Anaconda's side... I am fine with the change

**Review by katietz — APPROVED** [review]
Thanks

**Comment by jakirkham** [comment]
Thanks for taking another look Kai! 😄

**Pull request merged**
